version: "3.8"
services:
  fastapi:
    build:
      context: ../Pipeline_Summative/main.py  # Path to your FastAPI project
    container_name: fraud-catcher
    networks:
      - app-network
    ports:
      - "8000:8000"

  flask:
    build:
      context: ./app  # Path to your Flask project
    container_name: flask-app
    networks:
      - app-network
    ports:
      - "5000:5000"

networks:
  app-network:
    driver: bridge